-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 11-01-2025 a las 17:29:04
-- Versión del servidor: 10.4.32-MariaDB
-- Versión de PHP: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `canciones`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `songs`
--
-- Creación: 08-01-2025 a las 03:02:28
--

CREATE TABLE `songs` (
  `id` int(11) NOT NULL,
  `category` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `details` text NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Volcado de datos para la tabla `songs`
--

INSERT INTO `songs` (`id`, `category`, `name`, `details`, `created_at`) VALUES
(2, 'Alabanzas', 'Libre', 'Libre yo soy libre\r\n\r\n    D                         Esus4-E\r\nlas cadenas del pecado han sido rotas.\r\n\r\n A             F#m\r\nLibre yo soy libre\r\n\r\n        D          (Esus4)7           A\r\npara cantar para danzar para gozar.\r\n\r\n\r\nCORO:\r\n     F#m            E\r\nHe vencido, al enemigo\r\n\r\n         D            (Esus4)7      A\r\npor la sangre de Jesucristo yo soy libre.', '2025-01-08 04:16:06'),
(3, 'Alabanzas', 'Resplandece', 'D                      Dsus    D     C  G\r\nResplandece, pues ha venido tu luz\r\nD                      Dsus    D  D7\r\nResplandece, pues ha venido tu luz\r\n\r\n\r\nCORO:\r\n    G9                    Bm\r\nLa Gloria de Jehová ha nacido\r\n    Em7                     G\r\nLa Gloria de Jehová está aquí\r\n    Em                    Asus\r\nLa Gloria de Jehová ha venido\r\n  A7   D\r\nSobre Ti', '2025-01-08 04:16:06'),
(4, 'Alabanzas', 'Fiesta', 'Intro:\r\n\r\nCm  Fm  Bb G (Ab-G Ab-G Ab)x2\r\n\r\nVerso:\r\n           Cm                   Fm\r\nLo que se canta en el cielo, cantamos en la tierra\r\n            Bb                   G\r\nAl que se adora en el cielo, Adoramos en la tierra\r\n           Cm                   Fm\r\nLo que se canta en el cielo, cantamos en la tierra\r\n            Bb(C-D-Eb G-Ab-F-G-Ab-F-G)         G\r\nAl que se adora en el cielo, adoramos en la tierra\r\n\r\nPrecoro:\r\n    Ab            Gm                   Fm         Eb         G\r\nAl Santo (Santo), Digno (Digno), al Cordero (Cordero), que vive para siempre\r\n\r\nHacemos\r\nCm                       Fm\r\n Fiesta, hoy hacemos una fiesta\r\nBb                                       G (Ab-G Ab-G Ab-G )\r\nUnidos hoy danzamos con gozo celebramos, oh uh oh uh oh\r\nCm                       Fm\r\nFiesta, Hoy hacemos una fiesta\r\nBb                                     G (Ab-G Ab-G Ab-Bb)\r\nEn la tierra cantamos juntos gritamos, oh uh oh uh oh\r\n\r\nIntro x1\r\n\r\n\r\nVerso x1\r\n\r\n\r\nPrecoro x1\r\n\r\n\r\nCoro x1\r\n\r\nPuente\r\n\r\nC-C-C Eb-F-C-Eb-Eb-C\r\nBb-C-Bb-G-Bb-A-Eb\r\nEb-F-C-Eb-Eb-C\r\n\r\nAcordes: Cm  -  Eb  -  F  -  Bb  -  Cm\r\n\r\nPuente 2\r\n\r\n   Cm      Ab      Cm      Ab\r\nHacemos Fiesta, Hacemos Fiesta\r\n  Cm\r\nFiesta, Fiesta, Hacemos Fiesta, fiesta,\r\nHacemos Fiesta, Fiesta, Fiesta, fiesta//\r\n\r\nCoro Final.\r\nCm                       Fm\r\n Fiesta, hoy hacemos una fiesta\r\nBb                                       G (Ab-G Ab-G Ab-G )\r\nUnidos hoy danzamos con gozo celebramos, oh uh oh uh oh\r\nCm                       Fm\r\nFiesta, Hoy hacemos una fiesta\r\nBb                                     G (Ab-G Ab-G Ab-Bb)\r\nEn la tierra cantamos juntos gritamos, oh uh oh uh oh', '2025-01-08 04:29:44'),
(5, 'Alabanzas', 'Toda la noche-Con oleo de alegria', '     Cm                       A#  \r\n Con oleo de alegría me has ungido.  \r\n\r\n     G#                     G7  \r\nCon gozo y con pandero danzaré.  \r\n\r\n  Cm                     A#  \r\nDelante de tu pueblo redimido  \r\n\r\n     G#                     G7     \r\nla gloria de tu Nombre exaltaré\r\n\r\n          Cm \r\ncon el pandero. \r\n\r\n  \r\n\r\n Cm  \r\nToda la noche sin parar,  \r\n\r\n   A#  \r\ncantando alabanzas al Señor,  \r\n\r\n    G#  \r\ndiciendo de Su Gloria y Majestad,  \r\n\r\n             G7            Cm  \r\n\r\n   El es el Rey // (De Israel).', '2025-01-08 04:29:44'),
(6, 'Alabanzas', 'El señor es mi rey mi todo', '               Cm        A#\r\nEl Señor es mi rey, mi todo\r\n\r\nCm                Cm       A#\r\n   el Señor es mi luz, mi rey...\r\n\r\nG#                   G#     D#\r\n  el que me hace vibrar de gozo\r\nG#                 D#\r\n  el que guía mis pasos\r\nG#                     D#\r\n  el que extiende sus brazos\r\nG#                   D# A# Cm\r\n  el creador de los cie_e_los... (Sigue el Intro)', '2025-01-08 04:29:44'),
(7, 'Alabanzas', 'Cristo no esta muerto-La tengo', ' C\r\nCristo no está muerto (está vivo)\r\n F\r\nCristo no esta muerto (está vivo)\r\n C\r\nCristo no está muerto (está vivo)\r\n C                          C\r\nLo siento en mis manos, Lo siento en mis pies\r\n     C\r\nLo siento en todo mí ser\r\n\r\n C             F          C         F\r\nLa tengo, la tengo, la tengo, la tengo\r\n    G           G  F# F                           C\r\nLa unción está so-bre mi no la entiendo pero la tengo\r\n\r\n\r\nC                       F\r\nMira lo que hizo Dios, mira lo que hizo Dios\r\n C           F-F#-C         F-F#-C\r\nSano mi cuerpo,  tomo mi mente,  me salvo, justo a tiempo\r\n\r\n C                  F               F-F#-G\r\nSu nombre alabare, es el mismo de ayer\r\n           G-F#-F                  (C E F F# G A A# B C)\r\nLo alabaremos mira lo que hizo Dios\r\n\r\n\r\n     C         F        C        F\r\nLa tengo, la tengo, la tengo, la tengo\r\n    G           G-F#-F\r\nLa unción esta sobre mi gloria a Dios por que la\r\n  C\r\nTengo\r\n\r\nfinal son notas (C-C-E-E-F-F-F#-F#-G-A-A#-C) C', '2025-01-08 04:29:44'),
(8, 'Alabanzas', 'Remolineando', '            Cm\r\nhay muchas formas de alabar tu nombre\r\n          Bb           Cm\r\ny de exaltarte oh Jehova\r\n            G#    Bb         Cm\r\nhay muchas formas de magnificarte\r\n       G#   Bb      Cm\r\npero ahora lo are asi//\r\n\r\n       Cm                           Bb      Cm\r\nremolineando, remolineando, celebrare a Jehova\r\n                                         Bb\r\nremolineando, remolineando, me hare mas vil\r\n      G          Cm\r\npor causa de Jehova\r\n                                      Bb\r\nsaco mi vida del anonimato, me dio corona\r\n           Cm             G#        Bb         Cm\r\ny vestido real, asi es Jehova que exalta al pequeño\r\n           Bb    G             Cm\r\npor causa de el yo me hare mas vil//\r\nCm                          Bb         Cm\r\nlala lalalalalaila lalalalalaila lalalala//\r\n\r\nCm Bb/////\r\n\r\n       Cm                           Bb      Cm\r\nremolineando, remolineando, celebrare a Jehova\r\n       Cm\r\nremolineando, remolineando\r\n             Bb       G          Cm\r\nme hare mas vil por causa de Jehova', '2025-01-08 04:29:44'),
(9, 'Alabanzas', 'Asi como david cantaba', '  Cm                                        A#\r\n//Cuando el Señor hiciere volver la cautividad\r\n           Fm              G\r\n  seremos como los que sueñan//\r\n\r\n  Cm                       A#\r\n//Mi boca llenará de risa, mis labios de alabanza,\r\n  Fm\r\n  Entonces dirán las naciones:\r\n           G\r\n  Grandes cosas ha hecho el Señor//\r\n\r\n          Cm\r\n//Me gozaré, me gozaré, me gozaré,\r\n                    A#\r\n  me gozaré en Jehová.  [¡Gózate!]\r\n              Fm                          G\r\n  Pues ha llevado todo dolor, me ha hecho libre//\r\n\r\n\r\n  Cm                      A#\r\n//Así como David cantaba, así como David danzaba,\r\n  Fm                             G\r\n  así como David fluía en su presencia//', '2025-01-08 04:29:44'),
(10, 'Ofrendas', 'Bueno es alabar oh señor', 'G          C          D        C    D          \r\nbueno es alabar ¡oh señor!, tu nombre\r\nG              C       D       C    D        \r\ndarte honra gloria y honor por siempre,\r\nG           C       D                       \r\nbueno es alabarte jesus\r\n    Am7           D                        \r\ny gozarme en tu poder\r\n\r\n        G      C   D                         \r\nPORQUE GRANDE ERES TU\r\nG        C       D             \r\nGRANDES SON TUS OBRAS,\r\n        G     C    D                   \r\nPORQUE GRANDE ERES TU\r\n             Em                 D   \r\nGRANDE ES TU AMOR, GRANDE ES TU GLORIA.', '2025-01-08 04:29:44'),
(11, 'Adoraciones', 'Santo por siempre', 'VERSO1\r\nG                     C         G\r\nMil generaciones, Se postran a adorarle\r\n   Em            D           C\r\nLe cantan al cordero que venció\r\nG                          C                 G\r\nLos que nos precedieron, Y los que en El creerán\r\n    Em         D              C\r\nLe cantarán a aquel que ya venció\r\n\r\n\r\nPreCORO\r\n    C                  Em    D\r\nTu nombre es mas alto,    Tu nombre es mas grande\r\n    Em7          D    C         C               Em\r\nTu nombre, sobre todo es, Sean tronos, dominios\r\n   D                            Em    D    Am7\r\nPoderes, potestades, Tu nombre, sobre todo es\r\n\r\n\r\nCORO\r\n           C   Em   D                 G/B     Em7\r\nClaman ángeles Sa - anto, Clama la creación Santo.\r\n         Am7   Dsus4              G\r\nExaltado Dios  Santo,   Santo por siempre\r\n\r\n\r\nVERSO2\r\nG                    C            G\r\nSi te ha perdonado y tienes salvación\r\nEm7           D           C\r\nCántale al Cordero que venció\r\nG                      C                   G\r\nSi te ha libertado, Su nombre ha puesto en ti\r\nEm7           D            C  Em7  D                Am7\r\nCántale al cordero que venció,   Cantaremos siempre amén.\r\n\r\n\r\nCORO\r\n           C   Em   D                 G/B   Em7\r\nClaman ángeles Sa - anto, Clama la creación Santo.\r\n         Am7  Dsus4            G\r\nExaltado Dios Santo, Santo por siempre\r\n                   C   Em    D               G/B   Em7\r\nCanta el pueblo al Rey Sa - anto, Soberano es El, Santo\r\n               Am7    D              G\r\nY por siempre es,   Santo, Santo por siempre\r\n\r\n\r\nPreCORO\r\n    C                  Em      D\r\nTu nombre es mas alto,      Tu nombre es más grande\r\n   Em7           D    C          C                Em\r\nTu nombre, sobre todo es,   Sean tronos, dominios\r\n   D                Em7   D       C          Am\r\nPoderes, potestades,   Tu nombre, sobre todo es  //\r\n\r\n\r\nCORO\r\n\r\n\r\nOUTRO:        Am    D       G\r\nY por siempre es santo por siempre', '2025-01-08 04:29:44'),
(12, 'Ofrendas', 'Alabad a jehova', '       D  G       F#m7 Bm\r\nV) Alabad   a Jehová,\r\n            D/A            Bm7       A7\r\n   Naciones todas, Pueblos todos, alabadle\r\n          Em7         A7\r\n   Porque ha engrandecido\r\n           Em7    A7        D      A7\r\n   Sobre nosotros su misericordia\r\n\r\n\r\n             D  G        F#m7 Bm7\r\nV2) Y la verdad   de Jehová\r\n            F7/G         D      G\r\n    Es para siempre, aleluya, amén,\r\n            Cm7/Eb        D/A  Bm7\r\n    Y la verdad    de Jehová\r\n             Em7        A7      D\r\n    Es para siempre, aleluya, amén.\r\n\r\n\r\nOutro: Bm7         Em7         A7      D\r\n          …Es para siempre, aleluya, amén. [X2]  || G ||', '2025-01-08 04:29:44'),
(13, 'Adoraciones', 'Dios imparable', 'Intro A D F#m E\r\n\r\nA       D     F#m       E\r\nEres alabado, Eres exaltado\r\n   A           D       F#m        E\r\nTu nombre levantamos, aleluya, aleluya\r\n\r\nA       D    F#m         E\r\nEres adorado te glorificamos\r\n   A           D        F#m        E\r\nTu nombre levantamos, aleluya, aleluya\r\n\r\n\r\npre-coro\r\n\r\n      D  E  F#m       D  E   F#m\r\nA una so la voz, nos uni mos hoy\r\n       D E   F#m7           E\r\nTe canta mos Dios en adoración\r\n\r\n\r\ncoro\r\n          D                  E\r\nDios imparable, Dios de imposibles\r\n    A        E           F#m\r\nInigualable, eres invencible (x2)\r\n\r\n            D               E\r\nNo tengo temor en mi corazón, Tú tienes el\r\n     F#m7\r\ncontrol (x2)\r\n\r\n            Bm7   E              F#m7\r\nNo me falta nada     si te tengo a ti\r\n            Bm7   E                 A\r\nNo me falta nada     si te tengo a ti\r\n\r\n\r\npuente\r\n\r\n   F#m         E/G#    A  A/C#    Bm7\r\nY yo sé  quién va conmigo va  por mi\r\n      F#m      E/G# A    A/C#  Bm7\r\nY quien a  mis enem igos hace huir', '2025-01-08 04:29:44'),
(14, 'Adoraciones', 'Al estar aqui', '     A2           E/G#           F#m7    Em7\r\nAl estar en la presencia de Tu divinidad\r\n     A/C#  D2           Bm7        E/G#     D/F#  E/G#\r\ny al contemplar la hermosura de Tu santidad\r\n     A2         C#7         E/D  D   A/C#\r\nmi espíritu se alegra en Tu majestad\r\n    Bm7       D/A    Esus4  E\r\nte adoro a Tí,   te adoro a ti\r\n\r\n       A2         E/G#       F#m7       Em7\r\nCuando veo la grandeza de tu dulce amor\r\nA/C#  D2          Bm7        E/G#    D/F#  E/G#\r\ny  compruebo la pureza de Tu corazón\r\n     A2         C#7         E/D  D   A/C#\r\nmi espíritu se alegra en Tu majestad\r\n    Bm7       D/A    Esus4  E\r\nte adoro a Tí,   te adoro a Tí\r\n\r\n\r\nCoro:\r\n\r\n       A2          C#m7            E/D  D  A/C#\r\nY al estar aquí, delante de Tí te adooraré\r\n         Bm7         D/A         E/G#         D/F#\r\npostrado ante Tí, mi corazón te adora oh Dios\r\n  E/G#    A2             A/G\r\ny siempre quiero estar para adorar\r\n  D/F#          Dm/ F\r\ny contemplar Tu santidad\r\n    A/E         E2       D2  Dm     A2\r\nte adoro a Tí Señor, te adoooooro a Tí.', '2025-01-08 04:53:24'),
(15, 'Adoraciones', 'Siempre fiel', '[VERSO I]\r\n         D              E\r\nSi todo cae a mi alrededor\r\n         D                  E\r\nSi oscuridad cubre mi interior\r\n          A/C#  D  E\r\nTú permaneces\r\n          A/C#  D  E\r\nTú eres fuerte\r\n\r\n             D                E\r\nCuando el dolor llega al corazón\r\n        D              E\r\nY el temor nula mi visión\r\n          A/C#  D  E\r\nTú permaneces\r\n          A/C#  D  E\r\nTú eres fuerte\r\n\r\n[CORO]\r\n           A                      Bm\r\nConfío en ti, Dios, eres siempre fiel\r\n      F#m                  E\r\nNo temeré, Tú cuidarás de mí\r\n          D               E - A/#C\r\nNada se escapa de tu control\r\n             D                   E\r\nNada es más grande que nuestro Dios\r\n\r\n[INTERLUDIO]\r\nD   E   D   E\r\n\r\n[VERSO II]\r\n            D                  E\r\nSi ruge el mar para hundir tu voz\r\n         D                E\r\nY tempestad calla mi canción\r\n          A/C#  D  E\r\nTú permaneces\r\n          A/C#  D  E\r\nTú eres fuerte\r\n\r\n[CORO]x2\r\n           A                    Bm\r\nConfío en ti, Dios eres siempre fiel\r\n      F#m                  E\r\nNo temeré, Tú cuidarás de mí\r\n          D               E - A/#C\r\nNada se escapa de tu control\r\n             D                   E\r\nNada es más grande que nuestro Dios\r\n\r\n\r\n[INTERULDIO, PUENTE]\r\nF#m   A   F#m   A\r\n\r\n             F#m   D         A\r\nEspíritu de Dios, el consolador\r\n             F#m          D  A\r\nLlena mi interior con tu fuego\r\n             F#m  D          A\r\nEspíritu de Dios sopla otra vez\r\n             F#m       D  A\r\nVen, revive hoy estos huesos\r\n\r\n             D               E\r\nEspíritu de Dios, el consolador\r\n             F#m           A/C#\r\nLlena mi interior con tu fuego\r\n             D               E\r\nEspíritu de Dios sopla otra vez\r\n            F#m           E\r\nVen, revive hoy estos huesos\r\n\r\n[CORO]x2\r\n           A                    Bm\r\nConfío en ti, Dios eres siempre fiel\r\n      F#m                  E\r\nNo temeré, Tú cuidarás de mí\r\n          D               E - A/#C\r\nNada se escapa de tu control\r\n             D                   E\r\nNada es más grande que nuestro Dios\r\n\r\n             F#m   D         A\r\nEspíritu de Dios, el consolador\r\n             F#m          D  A\r\nLlena mi interior con tu fuego\r\n             F#m  D          A\r\nEspíritu de Dios sopla otra vez\r\n             F#m       D  A\r\nVen, revive hoy estos huesos', '2025-01-08 04:53:24');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `songs`
--
ALTER TABLE `songs`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `songs`
--
ALTER TABLE `songs`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=16;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
